name: Test Facebook Login

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-aichat:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'  # caching pip dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the login script (generates cookies.json if not found)
      - name: Login Facebook account
        run: |
          python fb_getcookies.py
        env:
          PYTHONUNBUFFERED: "1"